"""user foreign keys

Revision ID: 38ff575fff87
Revises: 5077f76d3a3
Create Date: 2015-11-15 19:45:23.591612

"""

# revision identifiers, used by Alembic.
revision = '38ff575fff87'
down_revision = '5077f76d3a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'bill_divisions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'bill_divisions', 'bills', ['bill_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bill_divisions', type_='foreignkey')
    op.drop_constraint(None, 'bill_divisions', type_='foreignkey')
    ### end Alembic commands ###
